### ISSUE TITLE
[BE] 1주차 1차 PR 반영

### ISSUE THREAD

**Issue by zbqmgldjfh** [zbqmgldjfh/issue-tracker#10]
## 📝 todo
- [x] IndexOutOfBoundsException 예외부분 고민하기
- [x] Log level 수정
- [x] (개인사항) url 시작 부분 다 /api prefix 추가하기
