### ISSUE TITLE
[BE] 2차 PR 반영하기

### ISSUE THREAD

**Issue by zbqmgldjfh** [zbqmgldjfh/issue-tracker#29]
## 📝 todo
- [ ] controller에서 header에 토큰 추가하던 부분을 interceptor로 옮기기
- [ ] Spring actuator 찾아보기
- [ ] 영속성 컨텍스트가 열려있는 상태 생각해보기
