### ISSUE TITLE
[BE] 3차 PR 반영하기

### ISSUE THREAD

**Issue by zbqmgldjfh** [zbqmgldjfh/issue-tracker#38]
## 📝 todo
- [x] nginx를 RHEL이나 RPM, apt로 까는 것과 직접 바이너리 다운로드/빌드 후 사용하는 것의 차이점도 한번 학습
- [x] Comment의 정적 create 메서드 고민해보기 
- [x] isSameCommentId equals로 변경하기
- [x] CommentService.addComment 테스트 작성해서 확인하기
- [x] Issues의 comments에 고아객체 삭제 추가하기
