### ISSUE TITLE
[BE] Entity 구현하기

### ISSUE THREAD

**Issue by zbqmgldjfh** [zbqmgldjfh/issue-tracker#4]
## 💡 issue
- [x] Entity를 구현한다.

## 📝 todo
- [x] 기존 물리적 ERD를 Entity로 변환한다.
- [ ] 의식적으로 1급 컬렉션을 적용한다.
- [x] 의식적으로 BaseEntity를 만들어 등록시간을 자동화 한다.
