### ISSUE TITLE
[BE] Issue API 구현 - 3

### ISSUE THREAD

**Issue by zbqmgldjfh** [zbqmgldjfh/issue-tracker#49]
## 📝 todo
- [x] 이슈 제목 편집
- [x]  이슈 담당자 가져오기
- [x]  이슈 담당자 선택
- [x]  이슈 레이블 가져오기
- [x]  이슈 레이블 선택
- [x]  이슈 마일스톤 가져오기
- [x]  이슈 마일스톤 선택
