### ISSUE TITLE
[FE] 로그인 연동

### ISSUE THREAD

**Issue by youryu0212** [zbqmgldjfh/issue-tracker#59]
## 💡 issue
Github 로그인 버튼을 누르면 로그인 후 이슈 페이지로 접속

## 📝 todo
- [ ] OAuth code 파싱
- [ ] 코드를 담아서 API 요청
- [ ] token을 쿠키(혹은 로컬스토리지)에 저장 후 이슈 페이지로 이동
